package seventhSession;

public class ExceptionHandlingExmple {
	public static void main(String[] args) {
		int a = 23;
		int b = 0;
		int result = 0;
		try {
			
			int[] array = { 1, 2 };
			System.out.println(array[2]);
			result = a / b;
			System.out.println("Completed division..");

		} catch (ArithmeticException exception) {
			b = 1;
			result = a / b;
			System.out.println("Arithmetic Exception has occured " + exception.getMessage());
		} catch (Exception ex) {
			System.out.println("Some exception has happened in program.." + ex);
		}
		
		finally{
			System.out.println("Part Of Finally Block. (A must Excecute block).");
		}
		
		System.out.println("The result is " + result);


	}
}
